In [1]:
import pandas as pd

In [2]:
ratings = pd.read_csv('data/RatingsV2.csv')
books = pd.read_csv('data/BooksV2.csv')

In [3]:
# ratings.drop(['Unnamed: 0'], axis=1, inplace=True)
# books.drop(['Unnamed: 0'], axis=1, inplace=True)

In [4]:
ratings = pd.merge(ratings, books, on='ISBN')

In [5]:
ratings.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 36323 entries, 0 to 36322
Data columns (total 14 columns):
 #   Column               Non-Null Count  Dtype  
---  ------               --------------  -----  
 0   Unnamed: 0           36323 non-null  int64  
 1   User-ID              36323 non-null  int64  
 2   ISBN                 36323 non-null  object 
 3   Book-Rating          36323 non-null  int64  
 4   Book-Title           36323 non-null  object 
 5   Book-Author          36323 non-null  object 
 6   Year-Of-Publication  36323 non-null  int64  
 7   Publisher            36323 non-null  object 
 8   Image-URL-L          36323 non-null  object 
 9   Author               35873 non-null  object 
 10  Summary              36323 non-null  object 
 11  Avg-Rating           36323 non-null  float64
 12  Count-Rating         36323 non-null  float64
 13  Genres               36323 non-null  object 
dtypes: float64(2), int64(4), object(8)
memory usage: 4.2+ MB


In [6]:
ratings = ratings[['Book-Title', 'User-ID']].reset_index(drop=True)
 
ratings

Book-Title  User-ID
0      Little Altars Everywhere        1
1      Little Altars Everywhere        2
2      Little Altars Everywhere        3
3      Little Altars Everywhere        4
4      Little Altars Everywhere        5
...                         ...      ...
36318         Judas, My Brother     9812
36319           The Dark Fields     9372
36320               Calico Bush    10744
36321               Calico Bush    13098
36322       Diplomatic Immunity     8932

[36323 rows x 2 columns]

In [7]:
books = books[['ISBN', 'Book-Title']]
books.head()

ISBN             Book-Title
0  0440234743          The Testament
1  0345402871               Airframe
2  0345417623               Timeline
3  0446310786  To Kill a Mockingbird
4  0060168013         Pigs in Heaven

In [8]:
books['Item-ID'] = books['ISBN'].astype('category').cat.codes + 1

In [9]:
books.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5067 entries, 0 to 5066
Data columns (total 3 columns):
 #   Column      Non-Null Count  Dtype 
---  ------      --------------  ----- 
 0   ISBN        5067 non-null   object
 1   Book-Title  5067 non-null   object
 2   Item-ID     5067 non-null   int16 
dtypes: int16(1), object(2)
memory usage: 89.2+ KB


In [10]:
books = books[['Item-ID', 'Book-Title']]
books.head()

Item-ID             Book-Title
0     2161          The Testament
1     1158               Airframe
2     1177               Timeline
3     2413  To Kill a Mockingbird
4       61         Pigs in Heaven

In [11]:
books['Item-ID'].nunique()

5067

In [12]:
from typing import Dict, Text
 
import numpy as np
import pandas as pd
import tensorflow as tf
 
import tensorflow_recommenders as tfrs 

2023-06-06 16:36:54.620195: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-06-06 16:36:55.141598: W tensorflow/compiler/xla/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2023-06-06 16:36:55.141789: I tensorflow/compiler/xla/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
2023-06-06 16:36:56.835166: W tensorflow/compiler/xla/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer.so.7'; dlerror: libnvinfer.so.7: cannot open shared object file: No such file or directory
2023-

In [13]:
ratings_df = ratings.copy()
books_df = books.copy()
 
 
ratings_df.rename(columns = {'Book-Title': 'book_title', 'User-ID' : 'user_id'}, inplace=True)
books_df.rename(columns = {'Book-Title': 'book_title', 'Item-ID' : 'item_id'}, inplace=True)

In [14]:
# import pickle5 as pickle

# pickle.dump(books_df, open('Books.pkl', 'wb'))
# # pickle.dump(ratings_df, open('Ratings.pkl', 'wb'))

In [15]:
# pickle.dump(books_df, open('Books.pkl', 'wb'))
# # pickle.dump(ratings_df, open('Ratings.pkl', 'wb'))

In [16]:
# cek = pickle.load(open('Books.pkl', 'rb'))
# cek.head()

item_id             book_title
0     2161          The Testament
1     1158               Airframe
2     1177               Timeline
3     2413  To Kill a Mockingbird
4       61         Pigs in Heaven

In [17]:
# convert them to tf datasets
ratings = tf.data.Dataset.from_tensor_slices(dict(ratings_df))
books = tf.data.Dataset.from_tensor_slices(dict(books_df))

2023-06-06 16:36:59.432349: W tensorflow/compiler/xla/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcuda.so.1'; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory
2023-06-06 16:36:59.432398: W tensorflow/compiler/xla/stream_executor/cuda/cuda_driver.cc:265] failed call to cuInit: UNKNOWN ERROR (303)
2023-06-06 16:36:59.432430: I tensorflow/compiler/xla/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (iqbalf-TUF-Gaming-FX505DY-FX505DY): /proc/driver/nvidia/version does not exist
2023-06-06 16:36:59.433040: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.


In [18]:
# import pickle5 as pickle
# # 
# pickle.dump(books, open('Books.pkl', 'wb'))
# pickle.dump(ratings, open('Ratings.pkl', 'wb'))

In [19]:
# get the first rows of the movies dataset
for m in books.take(5):
  print(m)

{'item_id': <tf.Tensor: shape=(), dtype=int16, numpy=2161>, 'book_title': <tf.Tensor: shape=(), dtype=string, numpy=b'The Testament'>}
{'item_id': <tf.Tensor: shape=(), dtype=int16, numpy=1158>, 'book_title': <tf.Tensor: shape=(), dtype=string, numpy=b'Airframe'>}
{'item_id': <tf.Tensor: shape=(), dtype=int16, numpy=1177>, 'book_title': <tf.Tensor: shape=(), dtype=string, numpy=b'Timeline'>}
{'item_id': <tf.Tensor: shape=(), dtype=int16, numpy=2413>, 'book_title': <tf.Tensor: shape=(), dtype=string, numpy=b'To Kill a Mockingbird'>}
{'item_id': <tf.Tensor: shape=(), dtype=int16, numpy=61>, 'book_title': <tf.Tensor: shape=(), dtype=string, numpy=b'Pigs in Heaven'>}


In [20]:
for r in ratings.take(5):
  print(r)

{'book_title': <tf.Tensor: shape=(), dtype=string, numpy=b'Little Altars Everywhere'>, 'user_id': <tf.Tensor: shape=(), dtype=int64, numpy=1>}
{'book_title': <tf.Tensor: shape=(), dtype=string, numpy=b'Little Altars Everywhere'>, 'user_id': <tf.Tensor: shape=(), dtype=int64, numpy=2>}
{'book_title': <tf.Tensor: shape=(), dtype=string, numpy=b'Little Altars Everywhere'>, 'user_id': <tf.Tensor: shape=(), dtype=int64, numpy=3>}
{'book_title': <tf.Tensor: shape=(), dtype=string, numpy=b'Little Altars Everywhere'>, 'user_id': <tf.Tensor: shape=(), dtype=int64, numpy=4>}
{'book_title': <tf.Tensor: shape=(), dtype=string, numpy=b'Little Altars Everywhere'>, 'user_id': <tf.Tensor: shape=(), dtype=int64, numpy=5>}


In [21]:
# Select the basic features.
ratings = ratings.map(lambda x: {
    "book_title": x["book_title"],
    "user_id": x["user_id"]
})
books = books.map(lambda x: x["book_title"])

Instructions for updating:
Lambda fuctions will be no more assumed to be used in the statement where they are used, or at least in the same block. https://github.com/tensorflow/tensorflow/issues/56089


In [22]:
# import pickle5 as pickle

# pickle.dump(books, open('Books.pkl', 'wb'))
# pickle.dump(ratings, open('Ratings.pkl', 'wb'))

In [23]:
user_ids_vocabulary = tf.keras.layers.IntegerLookup(mask_token=None)
user_ids_vocabulary.adapt(ratings.map(lambda x: x["user_id"]))
 
 
book_titles_vocabulary = tf.keras.layers.StringLookup(mask_token=None)
book_titles_vocabulary.adapt(books)

In [24]:
# import pickle5 as pickle
# # 
# pickle.dump(user_ids_vocabulary, open('User.pkl', 'wb'))
# pickle.dump(book_titles_vocabulary, open('Ratings.pkl', 'wb'))

In [25]:
class BookLensModel(tfrs.Model):
  # We derive from a custom base class to help reduce boilerplate. Under the hood,
  # these are still plain Keras Models.
 
  def __init__(
      self,
      user_model: tf.keras.Model,
      book_model: tf.keras.Model,
      task: tfrs.tasks.Retrieval):
    super().__init__()
 
    # Set up user and book representations.
    self.user_model = user_model
    self.book_model = book_model
 
    # Set up a retrieval task.
    self.task = task
 
  def compute_loss(self, features: Dict[Text, tf.Tensor], training=False) -> tf.Tensor:
    # Define how the loss is computed.
 
    user_embeddings = self.user_model(features["user_id"])
    book_embeddings = self.book_model(features["book_title"])
 
    return self.task(user_embeddings, book_embeddings)

In [26]:
# Define user and book models.
user_model = tf.keras.Sequential([
    user_ids_vocabulary,
    tf.keras.layers.Embedding(user_ids_vocabulary.vocabulary_size(), 64)
])
book_model = tf.keras.Sequential([
    book_titles_vocabulary,
    tf.keras.layers.Embedding(book_titles_vocabulary.vocabulary_size(), 64)
])
 
# Define your objectives.
task = tfrs.tasks.Retrieval(metrics=tfrs.metrics.FactorizedTopK(
    books.batch(128).map(book_model)
  )
)

In [27]:
# Create a retrieval model.
model = BookLensModel(user_model, book_model, task)
model.compile(optimizer=tf.keras.optimizers.Adagrad(0.5))
 
# Train for 3 epochs.
model.fit(ratings.batch(4096), epochs=3)

Epoch 1/3


2023-06-06 16:37:27.391454: W tensorflow/tsl/framework/cpu_allocator_impl.cc:82] Allocation of 67108864 exceeds 10% of free system memory.
2023-06-06 16:37:27.463280: W tensorflow/tsl/framework/cpu_allocator_impl.cc:82] Allocation of 67108864 exceeds 10% of free system memory.


1/9 [==>...........................] - ETA: 21s - factorized_top_k/top_1_categorical_accuracy: 2.4414e-04 - factorized_top_k/top_5_categorical_accuracy: 9.7656e-04 - factorized_top_k/top_10_categorical_accuracy: 0.0020 - factorized_top_k/top_50_categorical_accuracy: 0.0095 - factorized_top_k/top_100_categorical_accuracy: 0.0212 - loss: 34068.6328 - regularization_loss: 0.0000e+00 - total_loss: 34068.6328

2023-06-06 16:37:28.221361: W tensorflow/tsl/framework/cpu_allocator_impl.cc:82] Allocation of 67108864 exceeds 10% of free system memory.
2023-06-06 16:37:28.288821: W tensorflow/tsl/framework/cpu_allocator_impl.cc:82] Allocation of 67108864 exceeds 10% of free system memory.


2/9 [=====>........................] - ETA: 5s - factorized_top_k/top_1_categorical_accuracy: 1.2207e-04 - factorized_top_k/top_5_categorical_accuracy: 4.8828e-04 - factorized_top_k/top_10_categorical_accuracy: 9.7656e-04 - factorized_top_k/top_50_categorical_accuracy: 0.0063 - factorized_top_k/top_100_categorical_accuracy: 0.0182 - loss: 34068.9688 - regularization_loss: 0.0000e+00 - total_loss: 34068.9688

2023-06-06 16:37:29.065343: W tensorflow/tsl/framework/cpu_allocator_impl.cc:82] Allocation of 67108864 exceeds 10% of free system memory.


9/9 [==============================] - 8s 689ms/step - factorized_top_k/top_1_categorical_accuracy: 2.7531e-05 - factorized_top_k/top_5_categorical_accuracy: 2.4778e-04 - factorized_top_k/top_10_categorical_accuracy: 4.6802e-04 - factorized_top_k/top_50_categorical_accuracy: 0.0028 - factorized_top_k/top_100_categorical_accuracy: 0.0078 - loss: 33099.2660 - regularization_loss: 0.0000e+00 - total_loss: 33099.2660
Epoch 2/3
9/9 [==============================] - 6s 681ms/step - factorized_top_k/top_1_categorical_accuracy: 1.9272e-04 - factorized_top_k/top_5_categorical_accuracy: 0.0039 - factorized_top_k/top_10_categorical_accuracy: 0.0115 - factorized_top_k/top_50_categorical_accuracy: 0.0812 - factorized_top_k/top_100_categorical_accuracy: 0.1532 - loss: 32166.2381 - regularization_loss: 0.0000e+00 - total_loss: 32166.2381
Epoch 3/3
9/9 [==============================] - 6s 669ms/step - factorized_top_k/top_1_categorical_accuracy: 0.0884 - factorized_top_k/top_5_categorical_accuracy: 

In [28]:
# Use brute-force search to set up retrieval using the trained representations.
index = tfrs.layers.factorized_top_k.BruteForce(model.user_model)
index.index_from_dataset(
    books.batch(100).map(lambda title: (title, model.book_model(title))))

In [33]:
# Get some recommendations.
_, titles = index(np.array([225]))
print(f"Top 10 recommendations for user 42: {titles[0, :20]}")

Top 10 recommendations for user 42: [b'The Education of Little Tree' b'Virtual Light' b'Daggerspell'
 b'Ball Four' b'A Star Called Henry' b'Too Many Cooks'
 b'Rendezvous with Rama' b'Oryx and Crake' b'The Ugly Little Boy'
 b'Islands in the Net']


In [30]:
# get the users embeddings
users_embdeddings = user_model.weights[1].numpy()
 
# get the mapping of the user ids from the vocabulary
users_idx_name = user_ids_vocabulary.get_vocabulary()
 
# print the shape
users_embdeddings.shape

(16525, 64)

In [31]:
import pickle5 as pickle
# 
pickle.dump(user_ids_vocabulary, open('User.pkl', 'wb'))
pickle.dump(book_titles_vocabulary, open('Ratings.pkl', 'wb'))

InvalidArgumentError: Cannot convert a Tensor of dtype resource to a NumPy array.

In [34]:
# get the books embeddings
books_embdeddings = book_model.weights[1].numpy()
 
# get the mapping of the book tiles from the vocabulary
book_idx_name = book_titles_vocabulary.get_vocabulary()
 
# print the shape of the books embeddings
books_embdeddings.shape

(5068, 64)

In [35]:
book_model.predict(["Harry Potter and the Prisoner of Azkaban"])

1/1 [==============================] - 0s 103ms/step


array([[ 0.21487163, -0.33324146,  0.9501462 , -0.58884704,  1.0146874 ,
         0.28926226, -0.7476183 , -0.20930994,  0.8841889 , -0.7895067 ,
        -0.5174846 , -0.97731936,  1.1640527 , -1.1527156 ,  0.98859453,
         0.7890409 ,  1.0802909 , -0.5588331 , -1.0707998 , -1.2162035 ,
         0.60587025,  0.23181476,  0.3863407 , -0.12047958,  0.554301  ,
        -0.05788615, -1.000889  , -0.81643796, -0.39185366,  0.9952024 ,
        -0.78250194,  0.4419828 ,  1.0879096 , -0.9481119 , -0.8707744 ,
         0.6163281 , -0.5477191 ,  0.13775998, -0.84431195,  0.3503885 ,
         0.6223601 , -0.31119248, -0.85468984, -0.7074049 , -0.0397219 ,
        -0.8284998 , -0.8443066 ,  0.08627954,  0.22105277, -0.74575716,
        -0.5971295 , -0.871295  , -0.66443837, -0.14558679, -0.83842623,
         0.40966845,  1.0335081 ,  0.8783546 ,  0.65080297,  1.0187967 ,
         0.6595291 ,  0.24447107, -0.61808515,  0.0329106 ]],
      dtype=float32)

In [36]:
from sklearn.metrics import pairwise_distances
 
# get the cosine similarity of all pairs
books_similarity = 1-pairwise_distances(books_embdeddings, metric='cosine')
 
# get the upper triangle in order to take the unique pairs
books_similarity = np.triu(books_similarity)

In [37]:
book_A = np.take(book_idx_name, np.where((books_similarity>0.8))[0])
book_B = np.take(book_idx_name, np.where((books_similarity>0.8))[1])
 
similar_books = pd.DataFrame({'book_A':book_A, 'book_B':book_B})
similar_books.head(100)

book_A                 book_B
0             [UNK]                  [UNK]
1                 e                      e
2    Zuleika Dobson         Zuleika Dobson
3   Zorba the Greek        Zorba the Greek
4      Zombie Lover           Zombie Lover
..              ...                    ...
95         Wolfskin          Broken Angels
96         Wolfskin                    Bro
97         Wolfskin  Breaking and Entering
98         Wolfskin      Blackthorn Winter
99         Wolfskin                  Black

[100 rows x 2 columns]

In [38]:
similar_books.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8936 entries, 0 to 8935
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   book_A  8936 non-null   object
 1   book_B  8936 non-null   object
dtypes: object(2)
memory usage: 139.8+ KB


In [39]:
# get the product of users and movies embeddings
product_matrix = np.matmul(users_embdeddings, np.transpose(books_embdeddings))
 
# get the shape of the product matrix 
product_matrix.shape

(16525, 5068)

In [40]:
book_idx_name.index('Harry Potter and the Prisoner of Azkaban')

3549

In [41]:
# score of movies for book 42
book_42_books = product_matrix[book_idx_name.index("Harry Potter and the Prisoner of Azkaban"),:]
 
# return the top 10 books 
np.take(book_idx_name, book_42_books.argsort()[::-1])[0:10]

array(['Point of Origin', 'The Book of Fours',
       'The Lost Language of Cranes', 'The Bear and the Dragon',
       'Puerto Vallarta Squeeze', 'The Grass Crown', 'Ginger Pye',
       'Homecoming', 'The Murder of Roger Ackroyd', 'The River'],
      dtype='<U106')

In [43]:
# score of books for user 42
user_42_books = product_matrix[users_idx_name.index(225),:]
 
# return the top 10 books 
np.take(book_idx_name, user_42_books.argsort()[::-1])[0:10]

array(['The Education of Little Tree', 'Virtual Light', 'Daggerspell',
       'Ball Four', 'A Star Called Henry', 'Too Many Cooks',
       'Rendezvous with Rama', 'Oryx and Crake', 'The Ugly Little Boy',
       'Islands in the Net'], dtype='<U106')

In [44]:
seen_books = ratings_df.query('user_id==225')['book_title'].values
 
np.setdiff1d(np.take(book_idx_name, user_42_books.argsort()[::-1]), seen_books, assume_unique=True)[0:20]

array(['The Education of Little Tree', 'Virtual Light', 'Daggerspell',
       'Ball Four', 'A Star Called Henry', 'Too Many Cooks',
       'Rendezvous with Rama', 'Oryx and Crake', 'Islands in the Net',
       'The Murder of Roger Ackroyd', 'Only Human',
       'Puerto Vallarta Squeeze', 'Perelandra', 'The Joy Luck Club',
       'For Love of Mother-Not', 'Witches Abroad', 'The Europeans',
       'The House in Paris', 'Bloodsucking Fiends',
       'For Special Services'], dtype='<U106')

In [45]:
import tempfile
import os
# Export the query model.
# with tempfile.TemporaryDirectory() as tmp:
#   path = os.path.join(tmp, "model")
path = os.path.join('./', "model")
  # Save the index.
tf.saved_model.save(index, path)
 
  # Load it back; can also be done in TensorFlow Serving.


INFO:tensorflow:Assets written to: ./model/assets


INFO:tensorflow:Assets written to: ./model/assets


In [46]:
import tensorflow as tf
import os
path = os.path.join('./', "model")
loaded = tf.saved_model.load(path)

# Pass a user id in, get top predicted movie titles back.
scores, titles = loaded([225])
 
print(f"Recommendations: {titles[0][:5]}")

Recommendations: [b'The Education of Little Tree' b'Virtual Light' b'Daggerspell'
 b'Ball Four' b'A Star Called Henry']


In [47]:
loaded([225])

(<tf.Tensor: shape=(1, 10), dtype=float32, numpy=
 array([[2.5905342, 2.2789183, 2.225389 , 2.13339  , 2.1259413, 2.036004 ,
         1.9745611, 1.9689205, 1.929327 , 1.9255413]], dtype=float32)>,
 <tf.Tensor: shape=(1, 10), dtype=string, numpy=
 array([[b'The Education of Little Tree', b'Virtual Light',
         b'Daggerspell', b'Ball Four', b'A Star Called Henry',
         b'Too Many Cooks', b'Rendezvous with Rama', b'Oryx and Crake',
         b'The Ugly Little Boy', b'Islands in the Net']], dtype=object)>)